### PR TITLE
Release 0.9.0

### PR DESCRIPTION
**Pull request by SuperQ**
* Update VERSION.
* Update CHANGELOG.md.

### CODE REVIEW

**Comment by SuperQ** [comment]
CC: @roman-vynar Happy Percona Live Amsterdam 2016. :-)

**Comment by grypyrg** [comment]
👍

**Comment by roman-vynar** [comment]
Thanks @SuperQ ! However, I will miss this time 😇

**Comment by SuperQ** [comment]
So will I. :crying_cat_face:

**Comment by grypyrg** [comment]
No worries, I will sacrifice myself and drink all your beers!

**Comment by roman-vynar** [comment]
@grypyrg 👹

**Pull request merged**
