### PR TITLE
Release v0.10.0

### PR DESCRIPTION
**Pull request by SuperQ**
* [FEATURE] Add read/write query response time #166
* [FEATURE] Add Galera gcache size metric #169
* [FEATURE] Add MariaDB multi source replication support #178
* [FEATURE] Implement heartbeat metrics #183
* [FEATURE] Add basic file_summary_by_instance metrics #189
* [BUGFIX] Workaround MySQL bug 79533 #173

### CODE REVIEW

**Comment by roidelapluie** [comment]
Any news?

**Comment by SuperQ** [comment]
Ahh, sorry, this fell off my radar.

**Comment by filippog** [comment]
thanks @SuperQ! I was testing `0.10.0` today and noticed #178 has added a new `connection_name` key to `mysql_slave` metrics. Net effect being that slave metrics will be new metrics after the upgrade I think it should be pointed out in the changelog, WDYT?

**Comment by SuperQ** [comment]
Ahh, yes, I will update the changelog to mention that.

**Comment by SuperQ** [comment]
How does https://github.com/prometheus/mysqld_exporter/commit/accd5358eb57a376612cbf0c5c8584b11b21238a look?

**Comment by filippog** [comment]
@SuperQ :+1: thanks!

**Pull request merged**
