### PR TITLE
Set last_scrape_error when an error occurs

### LINKED ISSUE #216: mysql_exporter_last_scrape_error 0 when mysql_up is 0
`mysql_exporter_last_scrape_error` is reporting 0 (success) also when `mysql_up` is 0 (down). 

This is a bit confusing if we rely on `mysql_exporter_last_scrape_error` to check for failures. 

Steps to reproduce:
- start `mysqld_exporter`
- saturate the connection pool of the MySQL user used
- `mysqld_exporter` will report: 
```
Jul 03 06:21:41 bash[14316]: time="2017-07-03T06:21:41-07:00" level=error msg="Error pinging mysqld: Error 1226: User 'monitoring_a' has exceeded the 'max_user_connections' resource (current value: 3)" source="mysqld_exporter.go:269"
```
while returning
```
mysql_exporter_last_scrape_error 0
mysql_up 0
mysql_exporter_scrapes_total 6716
```

### PR DESCRIPTION
**Pull request by siavashs**
Closes #216

### CODE REVIEW

**Comment by arvenil** [comment]
Just my curiosity, but isn't this and similar metrics prone to race conditions? Exporter can receive in theory 2 requests at the same time, as I understand it will process both requests in parallel, as so two `Describe` methods will update this metric in `*Exporter` at the same time?

**Comment by arvenil** [comment]
@siavashs @SuperQ Just my curiosity, but isn't this and similar metrics prone to race conditions? Exporter can receive in theory 2 requests at the same time, as I understand it will process both requests in parallel, as so two `Describe` methods will update this metric in `*Exporter` at the same time? Or maybe default prometheus handler somehow queues requests?

**Comment by SuperQ** [comment]
Yes, I was just thinking about this yesterday and realized this isn't going to work.  We should be doing this via a Const metric.

**Comment by siavashs** [comment]
I think this should work fine since we create a new collector per request.

**Pull request merged**
