### PR TITLE
 Exposing ssl cert expiry metrics from show global status command output

### PR DESCRIPTION
**Pull request by prasanna2692**
mysql> show global status like 'ssl_server%';
+-----------------------+--------------------------+
| Variable_name         | Value                    |
+-----------------------+--------------------------+
| Ssl_server_not_after  | Dec 17 05:36:00 2021 GMT |
| Ssl_server_not_before | Dec 17 05:26:38 2020 GMT |
+-----------------------+--------------------------+
2 rows in set (0.00 sec)

Exposing this ssl metric to be used by prometheus to scrape and monitor ssl expiry for DB host

### CODE REVIEW

**Comment by prasanna2692** [comment]
Result after compiling:-

curl http://localhost:9104/metrics | grep -i ssl_server
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0# HELP mysql_global_status_mysqlx_ssl_server_not_after Generic metric from SHOW GLOBAL STATUS.
#TYPE mysql_global_status_mysqlx_ssl_server_not_after untyped
mysql_global_status_mysqlx_ssl_server_not_after 1.63971936e+09
#HELP mysql_global_status_mysqlx_ssl_server_not_before Generic metric from SHOW GLOBAL STATUS.
#TYPE mysql_global_status_mysqlx_ssl_server_not_before untyped 
mysql_global_status_mysqlx_ssl_server_not_before 1.608182798e+09
#HELP mysql_global_status_ssl_server_not_after Mysql server ssl certificate expiry end date.
#TYPE mysql_global_status_ssl_server_not_after gauge 

mysql_global_status_ssl_server_not_after 1.63971936e+09

#HELP mysql_global_status_ssl_server_not_before Mysql server ssl certificate expiry start date. 
#TYPE mysql_global_status_ssl_server_not_before gauge 

mysql_global_status_ssl_server_not_before 1.608182798e+09

100 554k 0 554k 0 0 3233k 0 --:--:-- --:--:-- --:--:-- 3420k

**Comment by mmiller1** [comment]
Is this different than what was done here by chance? https://github.com/prometheus/mysqld_exporter/pull/561

**Comment by prasanna2692** [comment]
Hi @mmiller1 ,
This PR is related to exposing SSL metrics for mysqld exporter.
It doesn't seem to related to PR #561

**Comment by mmiller1** [comment]
I mentioned because the PR was specifically made to address the SSL expirey issue. I believe it addresses it by parsing all "GLOBAL STATUS" variables that are dates as timestamps.

**Comment by prasanna2692** [comment]
Hi @mmiller1 
I see PR is merged but new release of exporter version came with that PR?
Because existing release i tested it was not there

**Comment by mmiller1** [comment]
Yes, a new release has not been cut in quite some time, but the code that provides this functionality is in the mainline branch. As I understand it there is currently a single maintainer for the project who is quite busy. You can verify the functionality by using one of the binaries from a more recent branch build (this is what we're currently deploying to our hosts https://app.circleci.com/pipelines/github/prometheus/mysqld_exporter/443/workflows/17bad152-9957-4ea9-8474-032a79021d0f/jobs/3835/artifacts)

**Comment by SuperQ** [comment]
Yes, this should be solved by #561.

**Comment by mathieu-souchet** [comment]
Hi,

I use latest version of `mysqld_exporter` (`v0.15.1`) and the metrics `mysql_global_status_ssl_server_not_before` and `mysql_global_status_ssl_server_not_after` are not available.

So I don't think issue #561 is resolved ... or I have missed something 🤷 

The only metrics I have are the following : 

```
# HELP mysql_global_status_ssl_accept_renegotiates Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_accept_renegotiates untyped
mysql_global_status_ssl_accept_renegotiates 0
# HELP mysql_global_status_ssl_accepts Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_accepts untyped
mysql_global_status_ssl_accepts 40
# HELP mysql_global_status_ssl_callback_cache_hits Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_callback_cache_hits untyped
mysql_global_status_ssl_callback_cache_hits 0
# HELP mysql_global_status_ssl_client_connects Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_client_connects untyped
mysql_global_status_ssl_client_connects 0
# HELP mysql_global_status_ssl_connect_renegotiates Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_connect_renegotiates untyped
mysql_global_status_ssl_connect_renegotiates 0
# HELP mysql_global_status_ssl_ctx_verify_depth Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_ctx_verify_depth untyped
mysql_global_status_ssl_ctx_verify_depth 1.8446744073709552e+19
# HELP mysql_global_status_ssl_ctx_verify_mode Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_ctx_verify_mode untyped
mysql_global_status_ssl_ctx_verify_mode 5
# HELP mysql_global_status_ssl_default_timeout Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_default_timeout untyped
mysql_global_status_ssl_default_timeout 0
# HELP mysql_global_status_ssl_finished_accepts Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_finished_accepts untyped
mysql_global_status_ssl_finished_accepts 40
# HELP mysql_global_status_ssl_finished_connects Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_finished_connects untyped
mysql_global_status_ssl_finished_connects 0
# HELP mysql_global_status_ssl_session_cache_hits Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_session_cache_hits untyped
mysql_global_status_ssl_session_cache_hits 0
# HELP mysql_global_status_ssl_session_cache_misses Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_session_cache_misses untyped
mysql_global_status_ssl_session_cache_misses 0
# HELP mysql_global_status_ssl_session_cache_overflows Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_session_cache_overflows untyped
mysql_global_status_ssl_session_cache_overflows 0
# HELP mysql_global_status_ssl_session_cache_size Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_session_cache_size untyped
mysql_global_status_ssl_session_cache_size 128
# HELP mysql_global_status_ssl_session_cache_timeouts Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_session_cache_timeouts untyped
mysql_global_status_ssl_session_cache_timeouts 0
# HELP mysql_global_status_ssl_sessions_reused Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_sessions_reused untyped
mysql_global_status_ssl_sessions_reused 0
# HELP mysql_global_status_ssl_used_session_cache_entries Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_used_session_cache_entries untyped
mysql_global_status_ssl_used_session_cache_entries 0
# HELP mysql_global_status_ssl_verify_depth Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_verify_depth untyped
mysql_global_status_ssl_verify_depth 0
# HELP mysql_global_status_ssl_verify_mode Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_ssl_verify_mode untyped
mysql_global_status_ssl_verify_mode 0
```

**Pull request closed without merging**
