### PR TITLE
fix binlog metrics on mysql 8.x

### PR DESCRIPTION
**Pull request by r0bj**
Mysql 8.x returns 3 columns during `SHOW BINARY LOGS` query instead of 2 in older mysql.

It fixes https://github.com/prometheus/mysqld_exporter/issues/413
It's based on @SuperQ comment in https://github.com/prometheus/mysqld_exporter/pull/390

### CODE REVIEW

**Comment by r0bj** [comment]
@SuperQ Those tests seems unstable, every time different one fails, some with `Failed to connect to github.com port 443: Connection timed out`.

**Comment by SuperQ** [comment]
I'm going to adjust the Travis test setup to only run the integration test, rather than a full test as we do that in CircleCI.

https://github.com/prometheus/mysqld_exporter/pull/420

**Comment by SuperQ** [comment]
Hrm, that didn't help at all. I'm guessing there's something wrong with Travis right now. It's usually reliable.

**Comment by SuperQ** [comment]
Retried the tests, looks like the Travis instability is fixed.

**Pull request merged**
