### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by SuperQ**
Don't use unnamed imports. :crying_cat_face:

### CODE REVIEW

**Comment by SuperQ** [comment]
@beorn7 :joy_cat:

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
:+1: 

It would be fine to use a different name (like a one-letter abbreviation). But not just nothing.

**Comment by SuperQ** [comment]
Yea, I think it's short enough as-is.

**Comment by roman-vynar** [comment]
That was their example 😇 https://github.com/smartystreets/goconvey#quick-start

**Comment by SuperQ** [comment]
Yea, apparently that's a bad recommendation according to Go standards.  I had no idea until @beorn7 pointed it out.

**Comment by beorn7** [comment]
For reference: https://github.com/golang/go/wiki/CodeReviewComments#import-dot

**Pull request merged**
