### PR TITLE
allow tls configurations

### PR DESCRIPTION
**Pull request by bluebrown**
Signed-off-by: Nico Braun <rainbowstack@gmail.com>

fix: #673

### CODE REVIEW

**Comment by SuperQ** [comment]
This needs a rebase with the new DSN formatter that was added.

CC @soara

**Comment by soara** [comment]
I think we should rewrite the code as below.

```diff
--- a/config/config_test.go
+++ b/config/config_test.go
@@ -197,12 +200,17 @@ func (m MySqlConfig) FormDSN(target string) (string, error) {
                config.Addr = target
        }
 
-       if m.SslCa != "" {
-               if err := m.CustomizeTLS(); err != nil {
-                       err = fmt.Errorf("failed to register a custom TLS configuration for mysql dsn: %w", err)
-                       return "", err
+       if m.TlsInsecureSkipVerify {
+               config.TLSConfig = "skip-verify"
+       } else {
+               config.TLSConfig = m.Tls
+               if m.SslCa != "" {
+                       if err := m.CustomizeTLS(); err != nil {
+                               err = fmt.Errorf("failed to register a custom TLS configuration for mysql dsn: %w", err)
+                               return "", err
+                       }
+                       config.TLSConfig = "custom"
                }
-               config.TLSConfig = "custom"
```

**Comment by SuperQ** [comment]
@soara Want to open a new PR?

**Comment by SuperQ** [comment]
Fixed in https://github.com/prometheus/mysqld_exporter/pull/718

**Pull request closed without merging**
