### PR TITLE
Add the ability to specify a file to read the DSN from.

### PR DESCRIPTION
**Pull request by bweston92**
This helps when using Docker secrets.

```
docker secret create mysql_exporter_dsn "dsn goes here"
docker service  create --name mysql_exporter -e DATA_SOURCE_NAME_FILE=/run/secrets/mysql_exporter_dsn --secret mysql_exporter_dsn prom/mysql_exporter
```

### CODE REVIEW

**Comment by brian-brazil** [comment]
If we're adding a config file, then environment variable support should really be removed as it's not considered secure by Prometheus: https://prometheus.io/docs/operating/security/#secrets

**Comment by SuperQ** [comment]
There is already DSN from file via the supported via the `my.cnf` style config file.

**Comment by bweston92** [comment]
@brian-brazil I agree but for intention of this PR is to have the ability to use Docker secrets.
@SuperQ that requires more work then using Docker secrets.

**Comment by bweston92** [comment]
@SuperQ I think you've closed that PR a bit premature to discussion. Docker secrets are also more secure then my.cnf file.

**Comment by SuperQ** [comment]
Using the my.cnf style is pretty easy.

```
docker secret create my.cnf my.cnf
```

Then you specify the config with `--config.my-cnf=/run/secrets/my.cnf`.

**Pull request closed without merging**
