### PR TITLE
Release version 0.8.1

### PR DESCRIPTION
**Pull request by SuperQ**
* [BUGFIX] Fix collect.info_schema.innodb_tablespaces #119
* [BUGFIX] Fix SLAVE STATUS "Connecting" #125
* [MISC] New release process using docker, circleci and a centralized building tool #120
* [MISC] Typos #121

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by sdurrheimer** [comment]
Any reason for the changelog being different from the PR description ?

You can also add that there is `-version` flag now.

**Comment by SuperQ** [comment]
Oh, I forgot to update the changelog file.

**Comment by sdurrheimer** [comment]
:+1:, even better with a signed tag ;)

**Comment by grobie** [comment]
LGTM

**Pull request merged**
