### PR TITLE
Update vendor github.com/prometheus/client_golang/...@v0.9.0

### PR DESCRIPTION
**Pull request by SuperQ**
Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by beorn7** [comment]
And BTW: I would also update prometheus/common to the latest tip of master. It contains improved rendering of the text format, with potentially huge impact.

**Comment by SuperQ** [comment]
Yes, I use version tagging with govendor wherever possible.

**Comment by beorn7** [comment]
> Yes, I use version tagging with govendor wherever possible.

I meant, does it support the "x" in v0.9.x, meaning to pick the latest 0.9 release.

**Comment by beorn7** [comment]
Now approving this even more strongly. :o)

**Comment by SuperQ** [comment]
Ohhh, I get it.. Yes, I think it does... let me try adding that change.

**Comment by AlekSi** [comment]
Thank you!

**Pull request merged**
