### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by SuperQ**
* Update to circleci 2.0
* Update Makefile to include new tests, style check, etc.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
Aren't we going to use the common makefile ?

https://github.com/prometheus/prometheus/blob/master/Makefile.common

**Comment by SuperQ** [comment]
Yea, I suppose I could do that.

**Comment by krasi-georgiev** [comment]
it could be a good test run. open an issue if there is a blocker so we can adjust.

**Comment by SuperQ** [comment]
@krasi-georgiev Ok, this should be ready for review.

**Pull request merged**
