### PR TITLE
[WIP] Add type mappings for slave/global status

### PR DESCRIPTION
**Pull request by SuperQ**
...

### CODE REVIEW

**Comment by roman-vynar** [comment]
Hello,

If this may help you, I just grabbed MySQL metric types from Percona Monitoring Plugins for Cacti https://github.com/percona/percona-monitoring-plugins:
```
weber@pluto:~$ cat git/percona-monitoring-plugins/cacti/definitions/mysql.def |grep -B 1 data_source_type_id|egrep -v "^--"|awk '!(NR%2){print$0p}{p=$0}'|awk '{print $4" "$3}'|sed "s/[',]//g"|sed 's/ 1/ gauge/'|sed 's/ 3/ counter/'|tr "[:upper:]" "[:lower:]"|sort
aborted_clients counter
aborted_connects counter
active_transactions gauge
adaptive_hash_memory gauge
additional_pool_alloc gauge
binary_log_space gauge
binlog_cache_disk_use counter
binlog_cache_use counter
bytes_received counter
bytes_sent counter
com_delete counter
com_delete_multi counter
com_insert counter
com_insert_select counter
com_load counter
com_replace counter
com_replace_select counter
com_select counter
com_update counter
com_update_multi counter
connections counter
created_tmp_disk_tables counter
created_tmp_files counter
created_tmp_tables counter
current_transactions gauge
database_pages gauge
dictionary_cache_memory gauge
file_fsyncs counter
file_reads counter
file_system_memory gauge
file_writes counter
free_pages gauge
handler_commit counter
handler_delete counter
handler_read_first counter
handler_read_key counter
handler_read_next counter
handler_read_prev counter
handler_read_rnd counter
handler_read_rnd_next counter
handler_rollback counter
handler_savepoint counter
handler_savepoint_rollback counter
handler_update counter
handler_write counter
hash_index_cells_total gauge
hash_index_cells_used gauge
history_list gauge
ibuf_cell_count gauge
ibuf_free_cells gauge
ibuf_inserts counter
ibuf_merged counter
ibuf_merges counter
ibuf_used_cells gauge
innodb_lock_structs gauge
innodb_lock_wait_secs gauge
innodb_locked_tables gauge
innodb_log_buffer_size gauge
innodb_row_lock_time counter
innodb_row_lock_waits counter
innodb_sem_wait_time_ms gauge
innodb_sem_waits gauge
innodb_tables_in_use gauge
innodb_transactions counter
key_buf_bytes_unflushed gauge
key_buf_bytes_used gauge
key_buffer_size gauge
key_read_requests counter
key_reads counter
key_write_requests counter
key_writes counter
lock_system_memory gauge
locked_transactions gauge
log_bytes_flushed counter
log_bytes_written counter
log_writes counter
max_connections gauge
max_used_connections gauge
modified_pages gauge
open_files gauge
open_tables gauge
opened_tables counter
os_waits counter
page_hash_memory gauge
pages_created counter
pages_read counter
pages_written counter
pending_aio_log_ios gauge
pending_aio_sync_ios gauge
pending_buf_pool_flushes gauge
pending_chkp_writes gauge
pending_ibuf_aio_reads gauge
pending_log_flushes gauge
pending_log_writes gauge
pending_normal_aio_reads gauge
pending_normal_aio_writes gauge
pool_read_requests counter
pool_reads counter
pool_size gauge
qcache_free_blocks gauge
qcache_free_memory gauge
qcache_hits counter
qcache_inserts counter
qcache_lowmem_prunes counter
qcache_not_cached counter
qcache_queries_in_cache gauge
qcache_total_blocks gauge
query_cache_size gauge
query_time_count_00 counter
query_time_count_01 counter
query_time_count_02 counter
query_time_count_03 counter
query_time_count_04 counter
query_time_count_05 counter
query_time_count_06 counter
query_time_count_07 counter
query_time_count_08 counter
query_time_count_09 counter
query_time_count_10 counter
query_time_count_11 counter
query_time_count_12 counter
query_time_count_13 counter
query_time_total_00 counter
query_time_total_01 counter
query_time_total_02 counter
query_time_total_03 counter
query_time_total_04 counter
query_time_total_05 counter
query_time_total_06 counter
query_time_total_07 counter
query_time_total_08 counter
query_time_total_09 counter
query_time_total_10 counter
query_time_total_11 counter
query_time_total_12 counter
query_time_total_13 counter
questions counter
read_views gauge
recovery_system_memory gauge
relay_log_space gauge
rows_deleted counter
rows_inserted counter
rows_read counter
rows_updated counter
select_full_join counter
select_full_range_join counter
select_range counter
select_range_check counter
select_scan counter
slave_lag gauge
slave_open_temp_tables gauge
slave_retried_transactions counter
slave_running gauge
slave_stopped gauge
slow_queries counter
sort_merge_passes counter
sort_range counter
sort_rows counter
sort_scan counter
spin_rounds counter
spin_waits counter
state_closing_tables gauge
state_copying_to_tmp_table gauge
state_end gauge
state_freeing_items gauge
state_init gauge
state_locked gauge
state_login gauge
state_none gauge
state_other gauge
state_preparing gauge
state_reading_from_net gauge
state_sending_data gauge
state_sorting_result gauge
state_statistics gauge
state_updating gauge
state_writing_to_net gauge
table_cache gauge
table_locks_immediate counter
table_locks_waited counter
thread_cache_size gauge
thread_hash_memory gauge
threads_cached gauge
threads_connected gauge
threads_connected gauge
threads_created counter
threads_running gauge
total_mem_alloc gauge
uncheckpointed_bytes gauge
unflushed_log gauge
```
Not all of them are from SHOW GLOBAL STATUS but the result from parsing SHOW ENGINE INNODB STATUS etc. See https://github.com/percona/percona-monitoring-plugins/blob/master/cacti/scripts/ss_get_mysql_stats.php#L326
BTW, it would be great if we can parse INNODB STATUS as well but that's tricky like in the script above.

**Comment by brian-brazil** [comment]
Percona's code is licensed under GPLv2, as Prometheus uses an Apache 2 license we can't use that. We'd need to build and maintain our own list from scratch.

**Comment by roman-vynar** [comment]
Brian, the idea was to help with defining those untyped metrics in mysqld_status_mappings.go.

About parsing INNODB STATUS, yeah I agree about building it from scratch.

**Comment by brian-brazil** [comment]
I'm afraid we can't to use the information you just provided, as it would be a violation of Percona's copyright. If you can get a release from Percona to let us use their code under an Apache 2 license then we can use it.

**Comment by rtreffer** [comment]
Now that percona is contributing missing stats anyway could we just close this as won't fix?

**Comment by SuperQ** [comment]
Yea, I was just looking at this PR a couple days ago and thinking it just wasn't worth the effort right now.

**Pull request closed without merging**
