### PR TITLE
 Add wsrep_evs_repl_latency metric

### PR DESCRIPTION
**Pull request by larrabee**
Hello.
This PR adds wsrep_evs_repl_latency metric collecting.

Closes: #309

### CODE REVIEW

**Comment by larrabee** [comment]
@SuperQ Done.

**Comment by SuperQ** [comment]
Two more small items.

Please sign off the individual commits with `git commit -s`.

To fix the codespell problem, please add `-L uint` to the end of the line in the https://github.com/prometheus/mysqld_exporter/blob/master/.circleci/config.yml#L23 config.

**Comment by larrabee** [comment]
I was squash all commits into one and sing-off it.

**Comment by larrabee** [comment]
Can you create new release? I want to use this version in prod.;)

**Comment by SuperQ** [comment]
Yes, I'll see if I can get a new release cut this week.

**Pull request merged**
